In [2]:
import pandas as pd

In [ ]:
#R에서 로딩이 안될시 사용

In [3]:
df = pd.read_csv("./CUST_ORDER_OUTPUT2.utf8.csv", encoding = 'utf-8')

c:\users\asiae_06\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
df

,LGROUP,MGROUP,SGROUP,DGROUP,LGROUP_NAME,MGROUP_NAME,SGROUP_NAME,DGROUP_NAME,LMSD_CODE
0,70,2,1,2,식품,신선식품/가공식품,간편/즉석식품,기타 간편/즉석식품,70020102
1,70,2,1,3,식품,신선식품/가공식품,간편/즉석식품,덮밥/덮밥소스,70020103
2,70,2,1,4,식품,신선식품/가공식품,간편/즉석식품,만두/딤섬,70020104
3,70,2,1,5,식품,신선식품/가공식품,간편/즉석식품,분말짜장/카레,70020105
4,70,2,1,6,식품,신선식품/가공식품,간편/즉석식품,샐러드,70020106
...,...,...,...,...,...,...,...,...,...
2314,10,1,10,2,패션/잡화,남성/캐주얼의류,트레이닝/이지웨어,트레이닝 상의,10011002
2315,10,1,10,3,패션/잡화,남성/캐주얼의류,트레이닝/이지웨어,트레이닝 하의,10011003
2316,10,1,10,4,패션/잡화,남성/캐주얼의류,트레이닝/이지웨어,트레이닝 셋트,10011004
2317,10,2,1,1,패션/잡화,여성/캐주얼의류,가죽/모피/무스탕,가죽/무스탕,10020101
2318,40,1,16,7,주방,주방용품/식기,후라이팬/양면팬/구이팬,후라이팬4종세트,40011607

In [4]:
df.to_csv('CUST_ORDER_OUTPUT2.utf8.csv', encoding = 'cp949')

In [5]:
df =pd.read_csv('./VHD_GOODSKIND.csv', encoding = 'utf-8')

In [6]:
df.to_csv('VHD_GOODSKIND.csv', encoding = 'cp949')